spring.application.name=UrbanTracker

# URL del servidor y base de datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/urbanTracker

# Usuario y contraseña de la base de datos
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Manejo de esquema)
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Configuración específica de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Crear esquemas automáticamente
spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.properties.hibernate.hbm2ddl.schema_generation.create_source=metadata
spring.jpa.properties.hibernate.hbm2ddl.schema_generation.drop_source=metadata

# Puerto del servidor
server.port=8085