spring.application.name=UrbanTracker

# Database configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/UrbanTracker

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=3427

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Execute DDL statements
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


# Hibernate configuration (Schema management)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in console
spring.jpa.show-sql=true

# PostgreSQL specific configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Create schemas automatically
spring.jpa.properties.hibernate.hbm2ddl.schema_generation.create_source=metadata
spring.jpa.properties.hibernate.hbm2ddl.schema_generation.drop_source=metadata

# Server port
server.port=8080

# Allow circular references (temporary for debugging)
#spring.main.allow-circular-references=true

# MQTT / Mosquitto settings
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=urbantracker-backend
mqtt.username=
mqtt.password=
mqtt.clean-session=true
mqtt.automatic-reconnect=true
mqtt.connection-timeout=10
mqtt.keep-alive-interval=20

# Gmail SMTP server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=urbantracker751@gmail.com
spring.mail.password=clwjsosznbigwgoh




