CREATE SCHEMA IF NOT EXISTS `monitoring`;
CREATE SCHEMA IF NOT EXISTS `reports`;
CREATE SCHEMA IF NOT EXISTS `routes`;
CREATE SCHEMA IF NOT EXISTS `security`;
CREATE SCHEMA IF NOT EXISTS `shared`;
CREATE SCHEMA IF NOT EXISTS `users`;
CREATE SCHEMA IF NOT EXISTS `vehicles`;